### ISSUE TITLE
Varying sizes of links, formatting looks wrong at the bottom

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#18]
https://oxford-dev.ukmsl.net/representation/common-rooms/ - the bottom row of this grid layout is displaying in a different format to the others. Would be better to be listed at the same size as the others with a gap at the end.

**Comment by keenanandrew** [comment]
Well spotted. Looking at the code, and seeing how it behaves on different screen sizes/orientations, I think it might be a little complicated to fix. The desired behaviour (gap at the end) does appear in some configurations:

![image](https://user-images.githubusercontent.com/63597895/212329527-7cb92c39-e2b9-473c-be4a-91b09943ad5f.png)


I think the fix will cause more issues than it solves; happy to hear arguments in favour of looking into it more deeply though.

Additionally, I have now rounded the bottom corners to match the patterns we discussed yesterday for articles/blogs/etc.

**Comment by keenanandrew** [comment]
I just... fixed this one by accident.

Issue was in the styling of this type of thing:

```
@media all and (min-width: 1200px) {
  #societies ul.msl_organisation_list li {
    width: calc(100% / 5 - 20px);
    max-width: calc(100% / 2 - 20px);
  }
}
```

I have deactivated this in global.css and now it doesn't try to widen the final row out to fill the gaps.
