### ISSUE TITLE
website preview logo stretching

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#19]
![logo preview](https://user-images.githubusercontent.com/119948648/212361333-599c3d3c-c76f-4058-aae8-cc09b6518839.PNG)

This is a minor issue but the logo in the preview (in chrome at least) looks stretched and a bit odd. On the left is the old website and the right is the new one. Could use with replacing/reformatting to fit better. Not urgent right now but a small detail that could be worth investigating

**Comment by keenanandrew** [comment]
That is odd @Oxford-SU - I've just checked both sites and the 'favicon' image is the same for both, at 1200 x 566.

[New site favicon](https://oxford-dev.ukmsl.net/assets/site_resources/favicon.png)
[Old site favicon](https://www.oxfordsu.org/assets/site_resources/favicon.png)

There must be a setting somewhere else that's telling one site to stretch the image.

Either way, we should replace the favicon image with something smaller and square, which will improve load time and prevent the stretching issue. 

Favicons should be square and a multiple of 48px wide (for some reason) - could you please create a 144px x 144px image and share it here or on Teams?

**Comment by Oxford-SU** [comment]
![144px logo](https://user-images.githubusercontent.com/119948648/212655751-c43395bc-77a2-4527-9e15-2ca506a07528.png)

Here's a new version of the logo. Hopefully this one works better :)

**Comment by keenanandrew** [comment]
Thanks - have changed them now. Looks slightly better but still very small. 

Perhaps just the SU part of the logo?
