### ISSUE TITLE
Old elections displaying on individual campaign pages

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#20]
https://oxford-dev.ukmsl.net/organisation/10479/ - linked for example

Old elections are displaying on the campaign pages that should be hidden, at least not to non-members. Is there a way for these to be hidden for non-members of the campaign organisation

**Comment by keenanandrew** [comment]
The issue is that long-past elections have not been archived, via the Elections admin area.

I have manually archived the irrelevant elections for CRAE, and will look for a way to archive non-recent elections in bulk as there's a LOT of them.

**Comment by keenanandrew** [comment]
Sorted for all Liberation and Sectional campaigns.
