### ISSUE TITLE
Moving Volunteering Portal

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#25]
![activities](https://user-images.githubusercontent.com/119948648/212895823-d261b5cb-7ca6-432f-8ff9-62b467e4ec4a.png)

_https://www.oxfordsu.org/activities/volunteering/ I can see that you have a root page named /activities/ on the old site with multiple child pages (attached screenshot). In order to have this on the new site, you'd need to create these pages manually and, once you have them, copy/paste the content from them (some more info about this from our KB: https://knowledge.ukmsl.com/kb/content/support/editpages/#Add%20pages)_ - This from Paloma in regards to moving the volunteering portal to the new page.

**Comment by keenanandrew** [comment]
Do you want me to do this? Happy to, just let me know

**Comment by Oxford-SU** [comment]
If you could that would be great. I trust your skills much more than mine!

**Comment by keenanandrew** [comment]
all of the below is just me keeping notes for myself

- [ ] Landing page - Section
- [ ] /awardsubmissions - 
- [ ] /browseproviders - widget?
- [ ] /formsubmission - where is form located
- [ ] /hours - ?
- [ ] /opportunities
- [ ] /profile - ?
- [ ] /providers
- [ ] /providers/details
- [ ] /providers/editopportunity
- [ ] /providers/listopportunities
- [ ] /providers/login
- [ ] /providers/register
- [ ] /providers/terms - copy/paste
- [ ] /record
- [ ] /review
- [ ] /tutorials - same as resources?

**Comment by keenanandrew** [comment]
Volunteering admin is buggy. Raised with MSL.

**Comment by keenanandrew** [comment]
MSL hadn't turned on the volunteering profile. This has now been done (https://oxford-dev.ukmsl.net/get-involved/volunteering/opportunities/)

Needs some restyling, and later will need reviewed by a relevant staff member to check the list of opportunities is up to date.

**Comment by keenanandrew** [comment]
The Volunteering section is live, but no longer listed on the navigation menu, as agreed with Hanne Clark on 28 Feb. 

The volunteering programme is not currently being actively managed or developed, which means the volunteering opportunities on there are no longer verified or reliable.

The section will be mothballed until there's a viable plan for the feature, or it's discontinued completely.
