### ISSUE TITLE
Training modules from old website not on new page

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#30]
Can we have the training modules appear along with the resources on the new page. The ones not showing yet are here on the old website: https://www.oxfordsu.org/support/training/

**Comment by keenanandrew** [comment]
Can do. Will be a little bit labour intensive as that training page works by showing an 'imagenavigation' widget, that shows the 'related image' from all of the child pages of /support/training, meaning they will need created as well.

Will investigate and report back

**Comment by keenanandrew** [comment]
Pages have now been created, and a couple have been given images. Widget design is powered by imageNav tag.

Next steps:

- [ ] Filter/search is not working
- [ ] Discuss what resources to keep with DO
- [ ] Review and transfer content for persisting resources

Deeper question: should Training and Resources be different formats?

![image](https://user-images.githubusercontent.com/63597895/213178427-2bf88c36-59f4-4c06-9cd1-94dd05a4ff7e.png)

**Comment by Oxford-SU** [comment]
I think they are fine in the same place. Especially as the training is often helpful alongside some of the resources if students are producing content for a project etc.
