### ISSUE TITLE
News articles missing heading in the blue header

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#32]
https://oxford-dev.ukmsl.net/news/article/17259/A-what-were-working-thing/ - can the blue section be smaller or contain a heading and/or an image.

**Comment by keenanandrew** [comment]
How odd... the h1 headline has disappeared. Will investigate template

**Comment by keenanandrew** [comment]
This issue fixed itself, which is nice.
