### ISSUE TITLE
Find solution for Find My Rep function

### ISSUE THREAD

**Issue by keenanandrew** [Oxford-SU/oxfordsu.org#46]
Currently https://www.oxfordsu.org/representation/academic-representation/findmyrep/ - extremely complicated, nested and non-functional way of showing reps.

Lots of the functionality here seems to be overengineered. 

What are the fundamentals of a Find My Rep function, and what is the simplest & most sustainable way to deliver them?

**Comment by keenanandrew** [comment]
The basic page has now been implemented, with a search function. 

https://oxford-dev.ukmsl.net/representation/academic-representation/find-your-rep/

All departments are listed together alphabetically, with no grouping by faculty.

Next steps:

- [ ] Is the department list up-to-date?
- [ ] What information should be shown on each department's page?
- [ ] How does the rep system work, structurally?
- [ ] Do we want an automatic "your rep is X" function, driven by course?
- [ ] Should this be the content of the Academic Representation landing page?

**Comment by Oxford-SU** [comment]
I think the pages just needed to show the list of reps and potentially a link to the departments own website. I will chat to Sameyia and ask if she can check the reps and confirm that the lists are up to date.

**Comment by keenanandrew** [comment]
A solution has been chosen: simply using Green Buttons with rep information added and updated manually. As of Feb 2023 there is no 'smart' connection between the website front end and MSL information about reps. Any such update will have to be preceded by work to ensure the MSL information is up to date and there is a staff-owned process to keep such information accurate.
