### ISSUE TITLE
Investigate the Policy Support page

### ISSUE THREAD

**Issue by keenanandrew** [Oxford-SU/oxfordsu.org#48]
https://www.oxfordsu.org/support/policy/

What is it, how does it work, who owns it, and is it necessary?

**Comment by keenanandrew** [comment]
Keep the Policy Guides? At least the content, if not the PDF format?

https://www.oxfordsu.org/support/policy/mental-health/

**Comment by Oxford-SU** [comment]
Looks like this would be owned by Sameyia and Hanne. The content on the child pages is needed.

**Comment by Oxford-SU** [comment]
Just had confirmation from Sameyia that the policy guides are being updated atm and will be ready for the end of term. I would recommend moving across all of the current content, even if the pages are blank and they will be updated later

**Comment by keenanandrew** [comment]
Sent to SS for signoff, 14 Feb 23

**Comment by keenanandrew** [comment]
Page is active but not linked in main menu, due to lack of content.

Actions sits with SS to review w/b 6 March 2023.
