### ISSUE TITLE
Resources need formatting to columns

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#7]
https://oxford-dev.ukmsl.net/opportunities/resources/ - in one long list, also does not need to display the categories and useful to sections

**Comment by keenanandrew** [comment]
Solved by the wider fix to the groupedlist widget styling.

Look how nice it is!

![image](https://user-images.githubusercontent.com/63597895/212703253-4e284092-13e5-417c-bff9-d997d906a483.png)

A future development may be to aid navigation by adding a category filter, but that's Another Day
