### ISSUE TITLE
Campaigns Pages Formatting

### ISSUE THREAD

**Issue by Oxford-SU** [Oxford-SU/oxfordsu.org#8]
The landing page needs columns added to display all and larger icons + sub pages need to be consistent with formatting and structure

**Comment by keenanandrew** [comment]
Initial thoughts: could this be solved easily by changing the page type? (Content with sidebar, for example)

If that doesn't work, then the column system from the Meet the Team page can be adopted and modified.

Any solution should (ideally) also be used consistently across similarly-designed pages

Will investigate.

**Comment by keenanandrew** [comment]
The campaigns landing page has now been mostly fixed, but the individual pages need formatting tweaks. I will create a separate issue for this as it will affect club & societies pages, and other 'organisations' shown on the site.
