### ISSUE TITLE
Make brand icons available on the website

### ISSUE THREAD

**Issue by keenanandrew** [Oxford-SU/oxfordsu.org#9]
Do we have the master files of the icons in the brand book? Screencap:
![image](https://user-images.githubusercontent.com/63597895/211866810-96098c86-2353-4f59-b3ef-50540f247f70.png)

We should upload them to the site so they can be referenced. For example, the book icon can be used on the green shape where resources such as the Articles of Association are indexed.

**Comment by Oxford-SU** [comment]
[Icons.zip](https://github.com/Oxford-SU/oxfordsu.org/files/10400642/Icons.zip)

This folder contains some of the icons above, I don't know where all of them will be but these are the ones most commonly used to my knowledge.

**Comment by keenanandrew** [comment]
Icons are now available site-wide, via the Scripts and Resources section

![image](https://user-images.githubusercontent.com/63597895/212700776-58ae8a6e-6f57-4a65-90ba-cab8168be90d.png)
